// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz3xJU_9nzs0Kb8q_pHDEtfvS8nstrEbI',
    appId: '1:651486664017:web:your-web-app-id',
    messagingSenderId: '651486664017',
    projectId: 'niladddata',
    authDomain: 'niladddata.firebaseapp.com',
    databaseURL: 'https://niladddata-default-rtdb.firebaseio.com',
    storageBucket: 'niladddata.firebasestorage.app',
    measurementId: 'your-measurement-id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3xJU_9nzs0Kb8q_pHDEtfvS8nstrEbI',
    appId: '1:651486664017:android:c1082bc88f512d9eb1ef70',
    messagingSenderId: '651486664017',
    projectId: 'niladddata',
    databaseURL: 'https://niladddata-default-rtdb.firebaseio.com',
    storageBucket: 'niladddata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz3xJU_9nzs0Kb8q_pHDEtfvS8nstrEbI',
    appId: '1:651486664017:ios:your-ios-app-id',
    messagingSenderId: '651486664017',
    projectId: 'niladddata',
    databaseURL: 'https://niladddata-default-rtdb.firebaseio.com',
    storageBucket: 'niladddata.firebasestorage.app',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.example.nileshGunaware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz3xJU_9nzs0Kb8q_pHDEtfvS8nstrEbI',
    appId: '1:651486664017:macos:your-macos-app-id',
    messagingSenderId: '651486664017',
    projectId: 'niladddata',
    databaseURL: 'https://niladddata-default-rtdb.firebaseio.com',
    storageBucket: 'niladddata.firebasestorage.app',
    iosClientId: 'your-macos-client-id',
    iosBundleId: 'com.example.nileshGunaware',
  );
} 